/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_dotstart_helios_game_RemoteGameProcess_DirectMemoryAccessor */

#ifndef _Included_io_github_dotstart_helios_game_RemoteGameProcess_DirectMemoryAccessor
#define _Included_io_github_dotstart_helios_game_RemoteGameProcess_DirectMemoryAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_dotstart_helios_game_RemoteGameProcess_DirectMemoryAccessor
 * Method:    read
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_github_dotstart_helios_game_RemoteGameProcess_00024DirectMemoryAccessor_read
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_github_dotstart_helios_game_RemoteGameProcess_DirectMemoryAccessor
 * Method:    write
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_github_dotstart_helios_game_RemoteGameProcess_00024DirectMemoryAccessor_write
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
