/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_dotstart_helios_game_DirectMemoryBinding */

#ifndef _Included_io_github_dotstart_helios_game_DirectMemoryBinding
#define _Included_io_github_dotstart_helios_game_DirectMemoryBinding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_dotstart_helios_game_DirectMemoryBinding
 * Method:    execute0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_dotstart_helios_game_DirectMemoryBinding_execute0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
