/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_dotstart_helios_game_RemoteGameProcess */

#ifndef _Included_io_github_dotstart_helios_game_RemoteGameProcess
#define _Included_io_github_dotstart_helios_game_RemoteGameProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_dotstart_helios_game_RemoteGameProcess
 * Method:    attach
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_dotstart_helios_game_RemoteGameProcess_attach
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
